apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pg7zrci22-python
  janus-idp.io/tekton: pg7zrci22-python
  backstage.io/kubernetes-id: pg7zrci22-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pg7zrci22-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
