apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pg7zrci22-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pg7zrci22-python 
  name: pg7zrci22-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pg7zrci22-python 
